backend:
  name: github
  repo: bytrangle/gatsby-demo
  branch: main

media_folder: uploads
public_folder: /uploads
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    label_singular: Post
    folder: content/netlify-cms
    preview_path: "blog/{{year}}/{{month}}/{{title}}"
    create: true
    fields:
      - { label: Title, name: title }
      - { label: Published Date, name: "published_date", widget: date }
      - {
          label: Updated Date,
          name: "updated_date",
          widget: date,
          default: false,
        }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Category,
          name: cat,
          widget: select,
          options: ["web development", "programming"],
          default: ["programming"],
        }
