backend:
  name: github
  repo: bytrangle/gatsby-demo
  branch: main

media_folder: uploads
public_folder: /uploads

collections:
  - name: blog
    label: Blog
    label_singular: Post
    folder: website/content/blog
    preview_path: "blog/{{year}}/{{month}}/{{title}}"
    create: true
    fields:
      - { label: Title, name: title }
      - { label: Date, name: date, widget: date }
      - { label: Body, name: body, widget: markdown }
